# Generated by Django 5.2.8 on 2026-08-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20, unique=True)),
                (
                    "faculty_1",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='First signature line, e.g. "Catherine Hall, Middle School Faculty"',
                        max_length=200,
                    ),
                ),
                (
                    "faculty_2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Second signature line",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["-label"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[("core", "Core Subject"), ("resource", "Resource")],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GradingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="reportcards.schoolyear",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="reportcards.schoolyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="reportcards.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Free-form grade, e.g. "83%", "P", "INC", "N/A"',
                        max_length=20,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("L", "Level"),
                            ("A", "Advanced"),
                            ("L/M", "Level/Modified"),
                            ("M", "Modified"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "work_habits",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Mastered"),
                            ("C", "Competent"),
                            ("I", "Improving"),
                            ("R", "Reminders Needed"),
                        ],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "grading_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="reportcards.gradingperiod",
                    ),
                ),
                (
                    "report_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="reportcards.reportcard",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="reportcards.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("absences", models.PositiveSmallIntegerField(default=0)),
                ("tardies", models.PositiveSmallIntegerField(default=0)),
                (
                    "grading_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="reportcards.gradingperiod",
                    ),
                ),
                (
                    "report_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="reportcards.reportcard",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report_card", "grading_period"),
                        name="unique_attendance_per_period",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="gradingperiod",
            constraint=models.UniqueConstraint(
                fields=("school_year", "name"), name="unique_period_name_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportcard",
            constraint=models.UniqueConstraint(
                fields=("student", "school_year"), name="unique_card_per_student_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("report_card", "subject", "grading_period"),
                name="unique_grade_per_cell",
            ),
        ),
    ]
